<?php

$equipment = [
  [ 'equip_id' => "E001", 'name' => "MacBook Pro 14", 'type_category' => "Laptop", 'total_qty' => 10, 'remain_qty' => 5, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E002", 'name' => "Dell UltraSharp 27", 'type_category' => "Monitor", 'total_qty' => 15, 'remain_qty' => 12, 'unit_id' => "UN02", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E003", 'name' => "Logitech MX Master 3", 'type_category' => "Mouse", 'total_qty' => 30, 'remain_qty' => 25, 'unit_id' => "UN01", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E004", 'name' => "Keychron K8", 'type_category' => "Keyboard", 'total_qty' => 20, 'remain_qty' => 18, 'unit_id' => "UN01", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E005", 'name' => "Cisco Catalyst 2960", 'type_category' => "Network Switch", 'total_qty' => 5, 'remain_qty' => 5, 'unit_id' => "UN02", 'dept_id' => "D003", 'status' => 'operational' ],
  [ 'equip_id' => "E006", 'name' => "HP LaserJet ProM404", 'type_category' => "Printer", 'total_qty' => 8, 'remain_qty' => 7, 'unit_id' => "UN02", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E007", 'name' => "Dell PowerEdge R740", 'type_category' => "Server", 'total_qty' => 3, 'remain_qty' => 3, 'unit_id' => "UN02", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E008", 'name' => "Lenovo ThinkPad X1", 'type_category' => "Laptop", 'total_qty' => 15, 'remain_qty' => 10, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E009", 'name' => "Ubiquiti UniFi AP", 'type_category' => "Access Point", 'total_qty' => 25, 'remain_qty' => 20, 'unit_id' => "UN02", 'dept_id' => "D003", 'status' => 'operational' ],
  [ 'equip_id' => "E010", 'name' => "Epson EcoTank L3150", 'type_category' => "Printer", 'total_qty' => 10, 'remain_qty' => 8, 'unit_id' => "UN02", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E011", 'name' => "Asus ROG Strix", 'type_category' => "Laptop", 'total_qty' => 5, 'remain_qty' => 5, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E012", 'name' => "Samsung Odyssey G7", 'type_category' => "Monitor", 'total_qty' => 12, 'remain_qty' => 10, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E013", 'name' => "Razer DeathAdder V2", 'type_category' => "Mouse", 'total_qty' => 25, 'remain_qty' => 20, 'unit_id' => "UN01", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E014", 'name' => "Corsair K95 RGB", 'type_category' => "Keyboard", 'total_qty' => 15, 'remain_qty' => 12, 'unit_id' => "UN01", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E015", 'name' => "Fortinet FortiGate", 'type_category' => "Firewall", 'total_qty' => 4, 'remain_qty' => 4, 'unit_id' => "UN02", 'dept_id' => "D003", 'status' => 'operational' ],
  [ 'equip_id' => "E016", 'name' => "Zebra ZD420", 'type_category' => "Barcode Printer", 'total_qty' => 10, 'remain_qty' => 9, 'unit_id' => "UN02", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E017", 'name' => "HPE ProLiant DL380", 'type_category' => "Server", 'total_qty' => 5, 'remain_qty' => 5, 'unit_id' => "UN02", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E018", 'name' => "Microtik RouterBoard", 'type_category' => "Router", 'total_qty' => 10, 'remain_qty' => 8, 'unit_id' => "UN02", 'dept_id' => "D003", 'status' => 'operational' ],
  [ 'equip_id' => "E019", 'name' => "APC Smart-UPS", 'type_category' => "UPS", 'total_qty' => 20, 'remain_qty' => 18, 'unit_id' => "UN02", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E020", 'name' => "Synology DiskStation", 'type_category' => "NAS", 'total_qty' => 6, 'remain_qty' => 6, 'unit_id' => "UN02", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E021", 'name' => "Apple iPad Pro", 'type_category' => "Tablet", 'total_qty' => 15, 'remain_qty' => 14, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E022", 'name' => "Microsoft Surface Pro", 'type_category' => "Tablet", 'total_qty' => 10, 'remain_qty' => 8, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E023", 'name' => "Logitech Brio 4K", 'type_category' => "Webcam", 'total_qty' => 30, 'remain_qty' => 28, 'unit_id' => "UN01", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E024", 'name' => "Jabra Speak 710", 'type_category' => "Speakerphone", 'total_qty' => 12, 'remain_qty' => 10, 'unit_id' => "UN01", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E025", 'name' => "Sony WH-1000XM4", 'type_category' => "Headset", 'total_qty' => 20, 'remain_qty' => 18, 'unit_id' => "UN01", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E026", 'name' => "LG 27GN950-B", 'type_category' => "Monitor", 'total_qty' => 10, 'remain_qty' => 10, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E027", 'name' => "BenQ PD2700U", 'type_category' => "Monitor", 'total_qty' => 8, 'remain_qty' => 7, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E028", 'name' => "Ergotron Monitor Arm", 'type_category' => "Accessory", 'total_qty' => 40, 'remain_qty' => 35, 'unit_id' => "UN01", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E029", 'name' => "Secretlab Titan", 'type_category' => "Chair", 'total_qty' => 50, 'remain_qty' => 45, 'unit_id' => "UN01", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E030", 'name' => "IKEA Bekant Desk", 'type_category' => "Desk", 'total_qty' => 50, 'remain_qty' => 48, 'unit_id' => "UN01", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E031", 'name' => "Netgear Nighthawk", 'type_category' => "Router", 'total_qty' => 5, 'remain_qty' => 5, 'unit_id' => "UN02", 'dept_id' => "D003", 'status' => 'operational' ],
  [ 'equip_id' => "E032", 'name' => "Crucial MX500 1TB", 'type_category' => "Storage", 'total_qty' => 40, 'remain_qty' => 38, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E033", 'name' => "Samsung 970 EVO", 'type_category' => "Storage", 'total_qty' => 30, 'remain_qty' => 28, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E034", 'name' => "Kingston 16GB DDR4", 'type_category' => "Memory", 'total_qty' => 60, 'remain_qty' => 55, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E035", 'name' => "Corsair Vengeance 32GB", 'type_category' => "Memory", 'total_qty' => 40, 'remain_qty' => 40, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E036", 'name' => "Intel Core i7-12700K", 'type_category' => "Processor", 'total_qty' => 15, 'remain_qty' => 15, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E037", 'name' => "AMD Ryzen 9 5900X", 'type_category' => "Processor", 'total_qty' => 10, 'remain_qty' => 9, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E038", 'name' => "NVIDIA RTX 3080", 'type_category' => "Graphics Card", 'total_qty' => 8, 'remain_qty' => 7, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E039", 'name' => "ASUS TUF Gaming Board", 'type_category' => "Motherboard", 'total_qty' => 12, 'remain_qty' => 10, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E040", 'name' => "Seasonic Focus 750W", 'type_category' => "Power Supply", 'total_qty' => 20, 'remain_qty' => 19, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E041", 'name' => "Noctua NH-D15", 'type_category' => "Cooler", 'total_qty' => 15, 'remain_qty' => 14, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E042", 'name' => "APC Back-UPS 600", 'type_category' => "UPS", 'total_qty' => 25, 'remain_qty' => 24, 'unit_id' => "UN02", 'dept_id' => "D001", 'status' => 'operational' ],
  [ 'equip_id' => "E043", 'name' => "TP-Link 24-Port Switch", 'type_category' => "Network Switch", 'total_qty' => 8, 'remain_qty' => 8, 'unit_id' => "UN02", 'dept_id' => "D003", 'status' => 'operational' ],
  [ 'equip_id' => "E044", 'name' => "Cat6 Ethernet Cable", 'type_category' => "Cable", 'total_qty' => 10, 'remain_qty' => 9, 'unit_id' => "UN01", 'dept_id' => "D003", 'status' => 'operational' ],
  [ 'equip_id' => "E045", 'name' => "HDMI Cable 2m", 'type_category' => "Cable", 'total_qty' => 100, 'remain_qty' => 95, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E046", 'name' => "DisplayPort Cable 2m", 'type_category' => "Cable", 'total_qty' => 50, 'remain_qty' => 48, 'unit_id' => "UN01", 'dept_id' => "D004", 'status' => 'operational' ],
  [ 'equip_id' => "E047", 'name' => "Google Pixel 7a", 'type_category' => "Smartphone", 'total_qty' => 10, 'remain_qty' => 10, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E048", 'name' => "iPhone 14 Pro", 'type_category' => "Smartphone", 'total_qty' => 5, 'remain_qty' => 5, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E049", 'name' => "Wacom Intuos Pro", 'type_category' => "Drawing Tablet", 'total_qty' => 4, 'remain_qty' => 4, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E050", 'name' => "Raspberry Pi 4", 'type_category' => "Microcomputer", 'total_qty' => 20, 'remain_qty' => 18, 'unit_id' => "UN02", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E051", 'name' => "Arduino Uno R3", 'type_category' => "Microcontroller", 'total_qty' => 30, 'remain_qty' => 30, 'unit_id' => "UN01", 'dept_id' => "D002", 'status' => 'operational' ],
  [ 'equip_id' => "E052", 'name' => "Fluke 115 Multimeter", 'type_category' => "Tool", 'total_qty' => 5, 'remain_qty' => 5, 'unit_id' => "UN02", 'dept_id' => "D004", 'status' => 'operational' ]
];
